export const tiposBatimentos = {
  N: "Normal - N",
  L: "Bloqueio ramo Esq. - L",
  R: "Bloqueio ramo Dir. - R",
  B: "Bloqueio ramo - B",
  A: "Atrial prematuro - A",
  a: "Atrial prematuro aberr. - a",
  J: "Juncional prematuro - J",
  S: "Supraventricular - S",
  V: "Ventricular prematuro - V",
  r: "Ventricular R-on-T - r",
  F: "Fusão Ventricular+Normal - F",
  e: "Escape atrial - e",
  j: "Escape juncional - j",
  n: "Escape supraventricular - n",
  E: "Escape ventricular - E",
  "/": "Marcapasso - /",
  f: "Fusão Marcapasso+Normal - f",
  Q: "Não classificável - Q",
  "?": "Indefinido - ?",
  "+": "Marcapasso - +",
  "~": "Artefato - ~",
};
