export const tiposBatimentos = {
  N: "Normal",
  L: "Bloqueio ramo esq.",
  R: "Bloqueio ramo dir.",
  B: "Bloqueio de ramo",
  A: "Atrial prematuro",
  a: "Atrial prematuro aberrante",
  J: "Juncional prematuro",
  S: "Supraventricular prematuro",
  V: "Contração ventricular prematura",
  r: "Contração ventricular prematura R sobre T",
  F: "Fusão ventricular e normal",
  e: "Escape atrial",
  j: "Escape juncional",
  n: "Escape supraventricular",
  E: "Escape ventricular",
  "/": "Com marcapasso",
  f: "Fusão marcapasso e normal",
  Q: "Não classificável",
  "?": "Não classificado durante aprendizado",
  "[": "Início de flutter/fibrilação ventricular",
  "!": "Onda de flutter ventricular",
  "]": "Fim de flutter/fibrilação ventricular",
  x: "Onda P não conduzida (CAP bloqueada)",
  "(": "Início da onda",
  ")": "Fim da onda",
  p: "Pico da onda P",
  t: "Pico da onda T",
  u: "Pico da onda U",
  "`": "Junção PQ",
  "'": "Ponto J",
  "^": "Artefato de marcapasso não capturado",
  "|": "Artefato tipo QRS isolado",
  "~": "Mudança na qualidade do sinal",
  "+": "Mudança de ritmo",
  s: "Mudança de segmento ST",
  T: "Mudança de onda T",
  "*": "Sístole",
  D: "Diástole",
};
